version: '3'
services:
  web:
    build: ./provisioning
    image: laravel-web
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - ./:/application:cached

  queue-server:
    build: ./provisioning
    image: laravel-web
    command: php artisan queue:work
    depends_on:
      - db
    volumes:
      - ./:/application:cached

  db:
    image: mariadb:latest
    container_name: db
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=g@devpwd
      - MYSQL_DATABASE=phuketpearl
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./provisioning/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./public:/application/public:cached
    depends_on:
      - web

  redis:
    image: redis
    ports:
      - '6379:6379'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=db
      - "TZ=Asia/Bangkok"
    restart: always
    depends_on:
      - db
   ports:
      - 8090:80